name: Integration continue Python

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le depot
      uses: actions/checkout@v4

      - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

      - name: Lancer les tests unitaires
      run: python -m unittest -v
